on:
  push:
    branches: ["main", "staging"]
  workflow_dispatch:

# Cancel in-progress jobs or runs for the current workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20.x"

permissions:
  contents: read

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set_env.outputs.env_name }}
    steps:
      - name: Set environment name
        id: set_env
        run: |
          if [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "env_name=Development" >> $GITHUB_OUTPUT
          fi
  build:
    needs: [pre-build]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.pre-build.outputs.env_name }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: "0"

      - uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          prefix: SECRET_

      - uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(vars) }}
          prefix: VAR_

      - run: env
