on:
  push:
    branches: ["main", "staging"]
  workflow_dispatch:

# Cancel in-progress jobs or runs for the current workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20.x"

permissions:
  contents: read

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set_env.outputs.env_name }}
    steps:
      - name: Get branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Set environment name
        id: set_env
        run: |
          if [[ "${GIT_BRANCH_NAME}" == "staging" ]]; then
            echo "::set-output name=env_name::Development"
          fi
  build:
    needs: [pre-build]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.pre-build.outputs.env_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          prefix: SECRET_

      - uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(vars) }}
          prefix: VAR_

      - run: env
